#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
# HISTSIZE=1000000
# SAVEHIST=1000000
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH="$HOME/.local/bin":$PATH
export PATH=$HOME/.cargo/bin:$PATH
export EDITOR='nvim'
export VISUAL='nvim'
# export PATH=$HOME/.local/share/go/bin:$PATH
# export GOPATH=$HOME/.local/share/go
# export PATH=$HOME/.fnm:$PATH
# export PATH="$PATH:./node_modules/.bin"
# eval "$(fnm env)"
